### ISSUE TITLE
Submodule error

### ISSUE THREAD

**Issue by tomihisaw** [Legoless/OpenCV-Dynamic#1]
Hi,

First of all, I just wanted to thank you for working on the dynamic framework version of OpenCV. This will be a very useful update to the library for iOS!

I don't use submodules much so please correct me if I am misunderstanding something. But when I tried using the pod using `pod 'OpenCV-Dynamic', '~> 3.x'`, I got the following error:

```
[!] /bin/bash -c 
set -e
git submodule init
git submodule update
python opencv/platforms/ios/build_framework.py ios --dynamic
cp -a ./ios/opencv2.framework ./opencv2.framework

Submodule 'opencv' (https://github.com/Legoless/opencv.git) registered for path 'opencv'
Cloning into '/Users/tom/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.0-a7e25/opencv'...
error: no such remote ref b1106570afc3ffe2a83c2c618d9670d82927d13e
Fetched in submodule path 'opencv', but it did not contain b1106570afc3ffe2a83c2c618d9670d82927d13e. Direct fetching of that commit failed.
```
That remote ref seems to refer to an older commit of the submodule.

Also, when I cloned OpenCV-Dynamic and added the OpenCV submodule manually, it worked (I cloned the repo, fetched the submodule and commented out the git submodule commands in the podspec). Do you happen to have an idea what might be the problem? Could it be related to the way the submodule is commited in git?

Thanks,
Tom

**Comment by Legoless** [comment]
This is an issue, because I squashed commits when fixing some details in the build script (trying to get OpenCV community to merge updated build script in the master repository). Submodule is pointing to a non-existing commit at the moment, I'll update this later today. Thanks for reporting the issue!

**Comment by Legoless** [comment]
@tomihisaw Can you please try again with 3.2.1? Thanks!

**Comment by tomihisaw** [comment]
@Legoless - working now, thanks!

One issue I encountered was this though: https://github.com/opencv/opencv/issues/6114. I was able to get it working though by including opencv before UIKit.
