### ISSUE TITLE
Can't build CocoaPod

### ISSUE THREAD

**Issue by Yoric** [Legoless/OpenCV-Dynamic#3]
I'm using the following CocoaPod:

```ruby
platform :ios, '9.0'

workspace 'MyApp'

target 'MyApp' do
  use_frameworks!

  # Pods for MyApp
  pod 'OpenCV-Dynamic', '~> 3.x'

  target 'MyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

then running `pod install`

I get the following error:
```
/Users/david/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.2-81ec0/opencv/modules/core/src/arithm_simd.hpp:1200:29: error: use of undeclared identifier 'hasSIMD128'
    Div_SIMD() { haveSIMD = hasSIMD128(); }
```

Attaching full build logs.

[logs.txt](https://github.com/Legoless/OpenCV-Dynamic/files/735002/logs.txt)

I don't think it matters, but I have `cmake` 3.7.2 and `clang-800.0.42.1`.

**Comment by Legoless** [comment]
Hmm, there is likely to be a default setting that `xcodebuild` reads and screws it up. Or it could be something that was removed in newer Xcode. Clang and cmake versions look okay.

Which Xcode are you using and what is the output of `xcode-select --version`?

**Comment by Yoric** [comment]
I'm using XCode 8.2.1 and I get `xcode-select version 2343`.

**Comment by Legoless** [comment]
My xcode-select returns version `2347`. Can you try to reinstall command line tools with `xcode-select --install` and try again?

**Comment by Legoless** [comment]
And do a `pod update` first, I pushed a new version that uses main OpenCV repository instead of my fork.

**Comment by Yoric** [comment]
> Can you try to reinstall command line tools with xcode-select --install and try again?

According to `xcode-select --install`, it seems that it's done through the AppStore these days. Should I still do it?

**Comment by Yoric** [comment]
Updated `pod` (even `CocoaPods` itself, since there was apparently a new release), got essentially the same message:

[log.txt](https://github.com/Legoless/OpenCV-Dynamic/files/739149/log.txt)

I'll look into de/re-installing the XCode command-line tools.

**Comment by Yoric** [comment]
Well, according to both `softwareupdate` and AppStore, I have the latest version of xcode. Maybe you are using XCode 8.3 beta?

**Comment by Legoless** [comment]
I'm not using the Beta version. I'll have a detailed look, apparently there is some compiler option active that shouldn't be in your configuration.

**Comment by Yoric** [comment]
Would this be influenced by the settings in my current XCode project or is this a system-wide stuff?

I'm targeting iOS 10.2, btw.

**Comment by Legoless** [comment]
The target is good. Only the minimum target is defined, which is iOS 8.x. I'm doing a clean install right now, will let you know if I run into this issue.

**Comment by Yoric** [comment]
Important configuration note: I have MacPorts installed. I suppose that it may somehow interfere.

**Comment by Legoless** [comment]
I have tried by installing MacPorts as well, doesn't seem to be the issue. Looking more into it. It's gonna be hard to fix until I can reproduce the issue, it must be somewhere with build scripts though. Can you try cloning the opencv repository directly and building the framework manually by using this command: `python opencv/platforms/ios/build_framework.py ios --dynamic`?

And if this fails, please try also without `--dynamic` option.

Let me know how it goes.

**Comment by t1m0** [comment]
Hi,
I'm facing the same issue, was there any resolution.
MacBook-Pro:~ user$ /usr/bin/xcodebuild -version
Xcode 8.2.1
Build version 8C1002

MacBook-Pro:~ user$ gem query --local cocoapods

*** LOCAL GEMS ***

cocoapods (1.2.0, 1.1.1)
cocoapods-core (1.2.0, 1.1.1, 0.39.0, 0.37.2)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.3, 0.9.3, 0.9.1)
cocoapods-plugins (1.0.0, 0.4.2)
cocoapods-search (1.0.0, 0.1.0)
cocoapods-stats (1.0.0, 0.6.2)
cocoapods-trunk (1.1.2, 0.6.4, 0.6.1)
cocoapods-try (1.1.0, 0.5.1, 0.4.5)

MacBook-Pro:~ user$ python opencv/platforms/ios/build_framework.py ios
============================================================
ERROR: cannot use a string pattern on a bytes-like object
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 112, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 80, in _build
    xcode_ver = getXCodeMajor()
  File "opencv/platforms/ios/build_framework.py", line 42, in getXCodeMajor
    m = re.match(r'XCode\s+(\d)\..*', ret, flags=re.IGNORECASE)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
