### ISSUE TITLE
stuck at cloning

### ISSUE THREAD

**Issue by solarisis** [Legoless/OpenCV-Dynamic#7]
sudo softwareupdate -i Command Line Tools
Password:
Software Update Tool
Copyright 2002-2015 Apple Inc.

Command: No such update
Line: No such update
Tools: No such update
No updates are available.
xcode-select --version
xcode-select version 2345.1.
am stuck at
Submodule 'opencv' (https://github.com/opencv/opencv.git) registered for path 'opencv'
Cloning into '/Users/*****/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.4-8d4c9/opencv'...

**Comment by Legoless** [comment]
Not sure I can help you here with anything else than check your internet connection and GitHub connectivity. OpenCV is a large repository, so it might take a while for it to clone.
