### ISSUE TITLE
Are you planning on updating to 4.0.0-beta ?

### ISSUE THREAD

**Issue by SwiftyMicroServices** [Legoless/OpenCV-Dynamic#9]

**Comment by Jeehut** [comment]
The final version was already released two weeks ago. Any updates? @Legoless

**Comment by Legoless** [comment]
Will do it sometime this week, as soon as I find time @Dschee @SwiftyMicroServices ! :)

**Comment by Jeehut** [comment]
Please note that building version 4.0.0 failed for me, I reported the exact error [here](https://github.com/opencv/opencv/issues/13324#issuecomment-443726889). Any ideas?

**Comment by Legoless** [comment]
Will have a look once I get to it. I know it depends on local cmake and python settings, so could be your issue only.

**Comment by Jeehut** [comment]
See [alaleks comment](https://github.com/opencv/opencv/issues/13324#issuecomment-443733450) when you have a look at it, too. Haven't tried myself, but be a useful hint.

**Comment by Legoless** [comment]
@Dschee Building works for me, so it has to do something with your local python or cmake settings. ;)

**Comment by Jeehut** [comment]
Okay, thanks for testing and reporting it!

**Comment by Legoless** [comment]
Went to 4.0.0 final release, should be available on CocoaPods.
